# Health Burden

## Set up

In [46]:
# Read in data
import pandas
data = pandas.read_csv('./data/prepped/risk-data.csv')

## Data Structure
To get a basic sense of your dataset, check the following:

- How large is the dataset (rows, columns)?
- What are the variables present in the dataset?
- What is the data type of each variable?

In [47]:
# dataset size
shape = data.shape
print("rows=%d, cols=%d" % shape)
print()

# variables present in dataset
names = data.columns.values
print('Column names:')
print(names)
print()

# data types of variables
dtypes = data.dtypes
print('Data types:')
print(dtypes)

rows=1950, cols=12

Column names:
['country' 'country.code' 'super.region' 'region' 'sex' 'age' 'pop'
 'alcohol.use' 'drug.use' 'high.meat' 'low.exercise' 'smoking']

Data types:
country          object
country.code     object
super.region     object
region           object
sex              object
age              object
pop             float64
alcohol.use     float64
drug.use        float64
high.meat       float64
low.exercise    float64
smoking         float64
dtype: object


## Univariate Analysis
For each variable of interest, answer the following questions. As you do so, begin making a list of further questions you would like to investigate:

- What does the distribution of each (risk factor) variable look like?
- Is any variable ever missing (and if so, why)?
- What are the basic summary statistics (mean, median, standard deviation) each variable, and what is it's range (min/max)?
- What do you find surprising?

In [62]:
# import plotly to graph distributions
from plotly.offline import plot
import plotly.graph_objs as go

alc_data = [go.Histogram(
    x=data.get('alcohol.use'),
)]

drug_data = [go.Histogram(
    x=data.get('drug.use'),
)]

meat_data = [go.Histogram(
    x=data.get('high.meat'),
)]

exc_data = [go.Histogram(
    x=data.get('low.exercise'),
)]

# plot data
plot(alc_data)
plot(drug_data)
plot(meat_data)
plot(exc_data)

'file:///Users/amberkim/Google Drive (uw)/INFO 370/eda/health-burden/temp-plot.html'

In [70]:
# any missing variables
#data.isnull()
missing = data['high.meat'].isnull()
data[missing]

,country,country.code,super.region,region,sex,age,pop,alcohol.use,drug.use,high.meat,low.exercise,smoking
2,China,CHN,"Southeast Asia, East Asia, and Oceania",East Asia,male,Under 5,4.458679e+07,0.236908,0.120827,NaN,NaN,NaN
3,China,CHN,"Southeast Asia, East Asia, and Oceania",East Asia,male,5-14 years,8.299538e+07,1.292633,0.038498,NaN,NaN,NaN
6,China,CHN,"Southeast Asia, East Asia, and Oceania",East Asia,female,5-14 years,7.148107e+07,0.868670,0.039037,NaN,NaN,NaN
8,China,CHN,"Southeast Asia, East Asia, and Oceania",East Asia,female,Under 5,3.854704e+07,0.183050,0.126190,NaN,NaN,NaN
10,North Korea,PRK,"Southeast Asia, East Asia, and Oceania",East Asia,male,Under 5,8.955102e+05,0.186889,0.101431,NaN,NaN,NaN
11,North Korea,PRK,"Southeast Asia, East Asia, and Oceania",East Asia,female,Under 5,8.553315e+05,0.195622,0.109240,NaN,NaN,NaN
15,North Korea,PRK,"Southeast Asia, East Asia, and Oceania",East Asia,male,5-14 years,1.826308e+06,1.078984,0.029139,NaN,NaN,NaN
18,North Korea,PRK,"Southeast Asia, East Asia, and Oceania",East Asia,female,5-14 years,1.751028e+06,0.709501,0.028816,NaN,NaN,NaN
23,Taiwan,TWN,"Southeast Asia, East Asia, and Oceania",East Asia,male,5-14 years,1.278556e+06,0.605018,0.006473,NaN,NaN,NaN
26,Taiwan,TWN,"Southeast Asia, East Asia, and Oceania",East Asia,female,5-14 years,1.167340e+06,0.424741,0.005962,NaN,NaN,NaN
28,Taiwan,TWN,"Southeast Asia, East Asia, and Oceania",East Asia,male,Under 5,5.332155e+05,0.146763,0.023686,NaN,NaN,NaN
29,Taiwan,TWN,"Southeast Asia, East Asia, and Oceania",East Asia,female,Under 5,4.875142e+05,0.150790,0.032121,NaN,NaN,NaN
32,Cambodia,KHM,"Southeast Asia, East Asia, and Oceania",Southeast Asia,female,5-14 years,1.548923e+06,0.382470,0.172875,NaN,NaN,NaN
36,Cambodia,KHM,"Southeast Asia, East Asia, and Oceania",Southeast Asia,male,Under 5,9.109717e+05,0.296777,0.460341,NaN,NaN,NaN
38,Cambodia,KHM,"Southeast Asia, East Asia, and Oceania",Southeast Asia,male,5-14 years,1.602495e+06,0.845309,0.146689,NaN,NaN,NaN
39,Cambodia,KHM,"Southeast Asia, East Asia, and Oceania",Southeast Asia,female,Under 5,8.751491e+05,0.274487,0.546200,NaN,NaN,NaN
40,Indonesia,IDN,"Southeast Asia, East Asia, and Oceania",Southeast Asia,male,5-14 years,2.390000e+07,0.166115,0.038020,NaN,NaN,NaN
41,Indonesia,IDN,"Southeast Asia, East Asia, and Oceania",Southeast Asia,female,Under 5,1.215305e+07,0.014568,0.245807,NaN,NaN,NaN
42,Indonesia,IDN,"Southeast Asia, East Asia, and Oceania",Southeast Asia,male,Under 5,1.264684e+07,0.022938,0.259538,NaN,NaN,NaN
47,Indonesia,IDN,"Southeast Asia, East Asia, and Oceania",Southeast Asia,female,5-14 years,2.250000e+07,0.062695,0.035421,NaN,NaN,NaN
56,Laos,LAO,"Southeast Asia, East Asia, and Oceania",Southeast Asia,female,5-14 years,7.484250e+05,0.508396,0.002537,NaN,NaN,NaN
57,Laos,LAO,"Southeast Asia, East Asia, and Oceania",Southeast Asia,male,Under 5,4.258995e+05,0.393618,0.011466,NaN,NaN,NaN
58,Laos,LAO,"Southeast Asia, East Asia, and Oceania",Southeast Asia,male,5-14 years,7.778120e+05,0.904358,0.003109,NaN,NaN,NaN
59,Laos,LAO,"Southeast Asia, East Asia, and Oceania",Southeast Asia,female,Under 5,4.101430e+05,0.405594,0.011983,NaN,NaN,NaN
60,Malaysia,MYS,"Southeast Asia, East Asia, and Oceania",Southeast Asia,male,Under 5,1.255658e+06,0.033275,0.172330,NaN,NaN,NaN
61,Malaysia,MYS,"Southeast Asia, East Asia, and Oceania",Southeast Asia,male,5-14 years,2.409461e+06,0.149386,0.168960,NaN,NaN,NaN
63,Malaysia,MYS,"Southeast Asia, East Asia, and Oceania",Southeast Asia,female,Under 5,1.185833e+06,0.037138,0.177175,NaN,NaN,NaN
65,Malaysia,MYS,"Southeast Asia, East Asia, and Oceania",Southeast Asia,female,5-14 years,2.546436e+06,0.066807,0.169868,NaN,NaN,NaN
75,Maldives,MDV,"Southeast Asia, East Asia, and Oceania",Southeast Asia,female,5-14 years,3.044700e+04,0.092604,0.007189,NaN,NaN,NaN
77,Maldives,MDV,"Southeast Asia, East Asia, and Oceania",Southeast Asia,male,Under 5,1.926674e+04,0.046948,0.017120,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1873,Mali,MLI,Sub-Saharan Africa,Western Sub-Saharan Africa,male,5-14 years,2.602835e+06,0.151282,0.162847,NaN,NaN,NaN
1875,Mali,MLI,Sub-Saharan Africa,Western Sub-Saharan Africa,female,Under 5,1.591175e+06,0.082074,0.340904,NaN,NaN,NaN
1884,Mauritania,MRT,Sub-Saharan Africa,Western Sub-Saharan Africa,female,5-14 years,5.057170e+05,0.014741,0.073656,NaN,NaN,NaN
1886,Mauritania,MRT,Sub-Saharan Africa,Western Sub-Saharan Africa,male,Under 5,3.152460e+05,0.012945,0.013295,NaN,NaN,NaN
1887,Mauritania,MRT,Sub-Saharan Africa,Western Sub-Saharan Africa,female,Under 5,3.029862e+05,0.010542,0.016521,NaN,NaN,NaN
1888,Mauritania,MRT,Sub-Saharan Africa,Western Sub-Saharan Africa,male,5-14 years,5.208940e+05,0.025807,0.070350,NaN,NaN,NaN
1891,Niger,NER,Sub-Saharan Africa,Western Sub-Saharan Africa,female,5-14 years,2.882715e+06,0.070706,0.144580,NaN,NaN,NaN
1893,Niger,NER,Sub-Saharan Africa,Western Sub-Saharan Africa,male,Under 5,2.092790e+06,0.045685,0.078472,NaN,NaN,NaN
1894,Niger,NER,Sub-Saharan Africa,Western Sub-Saharan Africa,male,5-14 years,3.014736e+06,0.106059,0.136633,NaN,NaN,NaN
1896,Niger,NER,Sub-Saharan Africa,Western Sub-Saharan Africa,female,Under 5,2.006993e+06,0.036360,0.085548,NaN,NaN,NaN
1904,Nigeria,NGA,Sub-Saharan Africa,Western Sub-Saharan Africa,female,5-14 years,2.390000e+07,0.316547,1.013988,NaN,NaN,NaN
1906,Nigeria,NGA,Sub-Saharan Africa,Western Sub-Saharan Africa,male,Under 5,1.604768e+07,0.357212,1.936762,NaN,NaN,NaN
1907,Nigeria,NGA,Sub-Saharan Africa,Western Sub-Saharan Africa,female,Under 5,1.528964e+07,0.337678,2.097706,NaN,NaN,NaN
1908,Nigeria,NGA,Sub-Saharan Africa,Western Sub-Saharan Africa,male,5-14 years,2.520000e+07,0.479977,0.959434,NaN,NaN,NaN
1911,Sao Tome and Principe,STP,Sub-Saharan Africa,Western Sub-Saharan Africa,female,5-14 years,2.559600e+04,0.295006,0.000099,NaN,NaN,NaN
1913,Sao Tome and Principe,STP,Sub-Saharan Africa,Western Sub-Saharan Africa,male,Under 5,1.533721e+04,0.539853,0.002275,NaN,NaN,NaN
1914,Sao Tome and Principe,STP,Sub-Saharan Africa,Western Sub-Saharan Africa,male,5-14 years,2.596700e+04,0.653128,0.000106,NaN,NaN,NaN
1916,Sao Tome and Principe,STP,Sub-Saharan Africa,Western Sub-Saharan Africa,female,Under 5,1.495766e+04,0.368042,0.003510,NaN,NaN,NaN
1924,Senegal,SEN,Sub-Saharan Africa,Western Sub-Saharan Africa,female,5-14 years,1.987082e+06,0.108259,0.074757,NaN,NaN,NaN
1926,Senegal,SEN,Sub-Saharan Africa,Western Sub-Saharan Africa,male,Under 5,1.308494e+06,0.076087,0.114549,NaN,NaN,NaN
1927,Senegal,SEN,Sub-Saharan Africa,Western Sub-Saharan Africa,male,5-14 years,2.032493e+06,0.186868,0.070512,NaN,NaN,NaN
1929,Senegal,SEN,Sub-Saharan Africa,Western Sub-Saharan Africa,female,Under 5,1.272743e+06,0.060337,0.123972,NaN,NaN,NaN
1930,Sierra Leone,SLE,Sub-Saharan Africa,Western Sub-Saharan Africa,male,Under 5,5.083643e+05,0.612461,0.087391,NaN,NaN,NaN
1933,Sierra Leone,SLE,Sub-Saharan Africa,Western Sub-Saharan Africa,female,5-14 years,8.675780e+05,0.664601,0.078851,NaN,NaN,NaN
1935,Sierra Leone,SLE,Sub-Saharan Africa,Western Sub-Saharan Africa,male,5-14 years,8.619320e+05,0.903488,0.076930,NaN,NaN,NaN
1936,Sierra Leone,SLE,Sub-Saharan Africa,Western Sub-Saharan Africa,female,Under 5,5.049774e+05,0.632909,0.092871,NaN,NaN,NaN
1941,Togo,TGO,Sub-Saharan Africa,Western Sub-Saharan Africa,female,5-14 years,9.601530e+05,0.238532,0.480699,NaN,NaN,NaN
1943,Togo,TGO,Sub-Saharan Africa,Western Sub-Saharan Africa,male,5-14 years,9.652130e+05,0.397258,0.454347,NaN,NaN,NaN
1945,Togo,TGO,Sub-Saharan Africa,Western Sub-Saharan Africa,female,Under 5,5.764667e+05,0.121739,0.278622,NaN,NaN,NaN
1946,Togo,TGO,Sub-Saharan Africa,Western Sub-Saharan Africa,male,Under 5,5.816957e+05,0.144637,0.260161,NaN,NaN,NaN

In [76]:
# summary statistics for each variable
print(data.describe())
print()
print('medians: ')
print(data.median())

                pop  alcohol.use     drug.use    high.meat  low.exercise  \
count  1.950000e+03  1950.000000  1950.000000  1170.000000   1170.000000
mean   3.777708e+06    47.146545     7.128357     2.594225    119.552443
std    1.913391e+07    86.009150    14.197640     4.043355    153.239610
min    3.563755e+02  -106.232008     0.000038     0.000176      0.308731
25%    1.000900e+05     0.273705     0.030068          NaN           NaN
50%    5.054975e+05     6.784878     1.917572          NaN           NaN
75%    2.071966e+06    54.987255     8.528416          NaN           NaN
max    3.901690e+08   662.914151   314.625888    36.087746    844.249502

           smoking
count  1170.000000
mean    299.520438
std     437.167168
min       0.532166
25%            NaN
50%            NaN
75%            NaN
max    2691.239677

medians:
pop             505497.500000
alcohol.use          6.784878
drug.use             1.917572
high.meat            0.817486
low.exercise        40.743931
smoking            105.816725
dtype: float64

//anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning:

Invalid value encountered in percentile

## Univariate analysis (by age)
In this section, you should investigate how each (risk-variable) varies by **age group**. More specifically, consider if the distribution of each variable of interest (smoking, alcohol use, etc.) is consistent across age-groups.

In [3]:
# Code goes here

## Univariate analysis (by sex)
In this section, you should investigate how each (risk-variable) varies by **sex group**. More specifically, consider if the distribution of each variable of interest (smoking, alcohol use, etc.) is consistent across sex-groups. Depending on your procedure, you may need to **reshape your data**.

In [4]:
# Code goes here

## Univariate analysis (by country)
In this section, you should investigate how each (risk-variable) varies by **country**. Given the number of countries present in the dataset, I suggest that you aggregate your data by region. In order to do this, you'll need to **convert death rates to deaths** using the `pop` column.

In [5]:
# Code goes here

## Bivariate analysis
In this section, you should compare risks-variables to one another to see how they co-vary. Use simple statistical tests (i.e., **correlation**) and visualization as you see fit.

In [6]:
# Code goes here